config/routes.rb
Rails.application.routes.draw do

  devise_for :podcasts
  root 'welcome#index'

  resources :podcasts, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email,
      :password, :password_confirmation, :title)}

    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:email,
      :password, :password_confirmation, :current_password, :title, :description,
      :itunes, :stitcher, :podbay)}
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    @podcasts = Podcast.all.order("created_at DESC")
  end

  def show
    @podcast = Podcast.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PodcastFm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Libre+Barcode+39+Text|Raleway" rel="stylesheet">
  </head>

  <% if alert %>
    <p class="alert">
      <%= alert %>
    </p>
  <% elsif notice %>
    <p class="notice">
      <%= notice %>
    </p>
  <% end %>
  <body>

    <header id="main_header" class="cf">
			<div class="wrapper_wide">
        <%= link_to "Podcast.fm", root_path, id:"logo" %>

				<nav>
					<ul>
            <% unless podcast_signed_in? %>
      				<li><%= link_to "Explore", podcasts_path %></li>
      				<li><%= link_to "Sign-in", new_podcast_session_path %></li>
      				<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
            <% else %>
            <li><a href="#">Dashboard</a></li>
              <li><%= link_to "Explore", podcasts_path %></li>
              <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
            <% end %>
					</ul>
				</nav>
			</div>
		</header>
    <%= yield %>
  </body>
</html>

app/views/podcasts/index.html.erb
<div id="banner" class="podcasts_banner">
  <h1>Discover your new favorite podcast.</h1>
</div>

  <div id="podcasts" class="cf">
    <div class="wrapper">
      <ul>
        <% @podcasts.each do |podcast| %>
          <%= link_to podcast do %>
          <li>
            <img src="images/about.jpg" alt="Narwhals Podcast">
            <div class="podcast_overview">
              <h2><%= podcast.title %></h2>
              <p class="episode_count">8 episodes</p>
            </div>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="pagination">
    <span class="previous_page disabled">Previous
    </span>
    <em class="current">1</em>
    <a href="#">2</a>
    <a href="#" class="next_page">Next</a>

  </div>

app/views/podcasts/show.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <% unless @podcast.itunes.blank? %>
        <a href="<% @podcast.itunes %>" class="subscribe_link">iTunes</a>
      <% end %>
      <% unless @podcast.stitcher.blank? %>
        <a href="<% @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
      <% end %>
      <% unless @podcast.podbay.blank? %>
        <a href="<% @podcast.podbay %>" class="subscribe_link">PodBay</a>
      <% end %>
    </div>
  </div>

  <div id="breadcrumb">
    <a href="#">
    <%= link_to podcasts_path do %>
      All Podcasts
      <span>/</span>
      The Rocketship Podcast
    <% end %>
    </a>
  </div>

  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <li class="cf">
          <div class="episode_thumbnail">
            <a href="#">
              <img src="images/pieterlevels.jpg" alt="Pheobe Judge">
            </a>
          </div>

          <div class="episode_overview">
            <h2><a href="episode.html">How to Pull Off 12 Startups in 12 Months</a></h2>
            <p class="description">
              Pieter Levels, Founder of Levels.io, talks about how he’s building 12 startups in 12 months. Not only do we cover how he’s able to pull that off (and to with awesome quality), but he has really interesting reasons why he’s approaching startups this way. This chat was incredibly inspiring and motivating - a must-listen.
            </p>
          </div>
        </li>

        <li class="cf">
          <div class="episode_thumbnail">
            <a href="episode.html">
              <img src="images/pieterlevels.jpg" alt="Pheobe Judge">
            </a>
          </div>

          <div class="episode_overview">
            <h2><a href="episode.html">How to Pull Off 12 Startups in 12 Months</a></h2>
            <p class="description">
              Pieter Levels, Founder of Levels.io, talks about how he’s building 12 startups in 12 months. Not only do we cover how he’s able to pull that off (and to with awesome quality), but he has really interesting reasons why he’s approaching startups this way. This chat was incredibly inspiring and motivating - a must-listen.
            </p>
          </div>
        </li>

        <li class="cf">
          <div class="episode_thumbnail">
            <a href="episode.html">
              <img src="images/pieterlevels.jpg" alt="Pheobe Judge">
            </a>
          </div>

          <div class="episode_overview">
            <h2><a href="episode.html">How to Pull Off 12 Startups in 12 Months</a></h2>
            <p class="description">
              Pieter Levels, Founder of Levels.io, talks about how he’s building 12 startups in 12 months. Not only do we cover how he’s able to pull that off (and to with awesome quality), but he has really interesting reasons why he’s approaching startups this way. This chat was incredibly inspiring and motivating - a must-listen.
            </p>
          </div>
        </li>

        <li class="cf">
          <div class="episode_thumbnail">
            <a href="episode.html">
              <img src="images/pieterlevels.jpg" alt="Pheobe Judge">
            </a>
          </div>

          <div class="episode_overview">
            <h2>
              <a href="episode.html">How to Pull Off 12 Startups in 12 Months</a>
            </h2>
            <p class="description">
              Pieter Levels, Founder of Levels.io, talks about how he’s building 12 startups in 12 months. Not only do we cover how he’s able to pull that off (and to with awesome quality), but he has really interesting reasons why he’s approaching startups this way. This chat was incredibly inspiring and motivating - a must-listen.
            </p>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="pagination">
    <span class="previous_page disabled">Previous
    </span>
    <em class="current">1</em>
    <a href="#">2</a>
    <a href="#" class="next_page">Next</a>
</div>

app/views/welcome/index.html.erb
<head>
  <title>Podcast.fm</title>
  <link rel="stylesheet" href="css/application.css">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Libre+Barcode+39+Text|Raleway" rel="stylesheet">
</head>

<div id="background">
	<header class="cf">
		<div class="wrapper_wide">
			<a href="index.html" id="logo">Podcast.fm</a>
		<nav>
			<ul>
        <% unless podcast_signed_in? %>
  				<li><%= link_to "Explore", podcasts_path %></li>
  				<li><%= link_to "Sign-in", new_podcast_session_path %></li>
  				<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
        <% else %>
        <li><a href="#">Dashboard</a></li>
          <li><%= link_to "Explore", podcasts_path %></li>
          <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
        <% end %>
      </ul>
		</nav>
		</div>
	</header>
	<div class="wrapper_skinny">
		<h1>Discover your new favorite <br> podcast, or create your own.</h1>
    <%= link_to "Create a Podcast", new_podcast_registration_path,
                class: "button button_highlight" %>
    <%= link_to "Explore", podcasts_path,
                class: "button button_white" %>

	</div>
</div>